-- Sky Hopper Phase 3. Applied through the project-scoped Supabase MCP.
create schema sky_hopper_private;
revoke all on schema sky_hopper_private from public, anon, authenticated;

create table public.user_skins (
  user_id uuid not null references auth.users(id) on delete cascade,
  skin_id text not null check (length(btrim(skin_id)) > 0),
  unlocked_at timestamptz not null default now(),
  primary key (user_id, skin_id)
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  total_coins integer not null default 0 check (total_coins >= 0),
  selected_skin text not null default 'default',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_selected_skin_fkey foreign key (id, selected_skin)
    references public.user_skins(user_id, skin_id) deferrable initially deferred
);

create table public.game_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  score integer not null check (score >= 0),
  height integer not null check (height >= 0),
  coins_collected integer not null default 0 check (coins_collected >= 0),
  played_at timestamptz not null default now()
);

create index game_scores_user_recent_idx on public.game_scores(user_id, played_at desc, id desc);
create index game_scores_score_idx on public.game_scores(score desc, played_at desc, id desc);
create index game_scores_played_at_idx on public.game_scores(played_at desc);

alter table public.profiles enable row level security;
alter table public.game_scores enable row level security;
alter table public.user_skins enable row level security;

-- Remove default API grants, then expose only the operations needed this phase.
revoke all on public.profiles, public.game_scores, public.user_skins from public, anon, authenticated;
revoke all on sequence public.game_scores_id_seq from public, anon, authenticated;
grant select on public.profiles, public.game_scores, public.user_skins to authenticated;
grant update (display_name, avatar_url, selected_skin) on public.profiles to authenticated;
grant insert (user_id, score, height, coins_collected) on public.game_scores to authenticated;
grant usage on sequence public.game_scores_id_seq to authenticated;

create policy profiles_select_own on public.profiles for select to authenticated
  using ((select auth.uid()) = id);
create policy profiles_update_own on public.profiles for update to authenticated
  using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
create policy game_scores_select_own on public.game_scores for select to authenticated
  using ((select auth.uid()) = user_id);
create policy game_scores_insert_own on public.game_scores for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy user_skins_select_own on public.user_skins for select to authenticated
  using ((select auth.uid()) = user_id);

create function sky_hopper_private.initialize_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.user_skins (user_id, skin_id)
  values (new.id, 'default')
  on conflict (user_id, skin_id) do nothing;

  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(
      nullif(btrim(new.raw_user_meta_data ->> 'full_name'), ''),
      nullif(btrim(new.raw_user_meta_data ->> 'name'), '')
    )
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create function sky_hopper_private.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function sky_hopper_private.initialize_user() from public, anon, authenticated;
revoke all on function sky_hopper_private.set_updated_at() from public, anon, authenticated;

create trigger sky_hopper_auth_user_created
after insert on auth.users
for each row execute function sky_hopper_private.initialize_user();

create trigger sky_hopper_profile_updated
before update on public.profiles
for each row execute function sky_hopper_private.set_updated_at();
