-- Sky Hopper Phase 12: UTC challenges, progression, rewards and competitions.
create table public.achievement_catalog (
  id text primary key check (id ~ '^[a-z][a-z0-9_]{0,39}$'),
  name text not null check (length(btrim(name)) > 0),
  description text not null check (length(btrim(description)) > 0),
  icon text not null check (icon ~ '^[a-z_]{1,30}$'),
  target integer not null check (target > 0),
  reward integer not null check (reward between 0 and 100),
  sort_order integer not null,
  is_active boolean not null default true
);

insert into public.achievement_catalog
  (id, name, description, icon, target, reward, sort_order)
values
  ('first_flight', 'FIRST FLIGHT', 'Complete a run', 'flight', 1, 5, 1),
  ('cloud_climber', 'CLOUD CLIMBER', 'Reach score 500', 'cloud', 500, 5, 2),
  ('storm_chaser', 'STORM CHASER', 'Reach the Storm biome', 'storm', 1, 10, 3),
  ('night_rider', 'NIGHT RIDER', 'Reach the Night biome', 'night', 1, 10, 4),
  ('to_the_stars', 'TO THE STARS', 'Reach Space', 'stars', 1, 15, 5),
  ('perfectionist', 'PERFECTIONIST', 'Reach a perfect streak of 5', 'perfect', 5, 10, 6),
  ('daredevil', 'DAREDEVIL', 'Record 10 near misses', 'danger', 10, 10, 7),
  ('coin_collector', 'COIN COLLECTOR', 'Collect 250 gameplay coins', 'coin', 250, 15, 8),
  ('high_flyer', 'HIGH FLYER', 'Reach score 2500', 'trophy', 2500, 20, 9),
  ('daily_player', 'DAILY PLAYER', 'Complete a Daily Challenge', 'calendar', 1, 5, 10),
  ('consistent', 'CONSISTENT', 'Complete Daily Challenges on 3 UTC dates', 'streak', 3, 15, 11);

create table public.run_progression (
  user_id uuid not null references auth.users(id) on delete cascade,
  run_id uuid not null,
  perfect_landings integer not null check (perfect_landings between 0 and 10000),
  best_perfect_streak integer not null check (best_perfect_streak between 0 and 10),
  near_misses integer not null check (near_misses between 0 and 10000),
  moving_landings integer not null check (moving_landings between 0 and 10000),
  highest_biome integer not null check (highest_biome between 0 and 4),
  is_daily boolean not null,
  recorded_at timestamptz not null default now(),
  primary key (user_id, run_id),
  foreign key (user_id, run_id) references public.game_scores(user_id, run_id)
);

create table public.daily_challenge_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  challenge_date date not null,
  run_id uuid not null,
  game_score_id bigint not null references public.game_scores(id) on delete cascade,
  attempt_number smallint not null check (attempt_number between 1 and 3),
  score integer not null check (score >= 0),
  height integer not null check (height >= 0),
  played_at timestamptz not null default now(),
  unique (user_id, run_id),
  unique (user_id, challenge_date, attempt_number),
  unique (game_score_id)
);

create table public.daily_missions (
  user_id uuid not null references auth.users(id) on delete cascade,
  mission_date date not null,
  mission_id text not null check (mission_id ~ '^[a-z][a-z0-9_]{0,39}$'),
  title text not null,
  description text not null,
  metric text not null,
  target integer not null check (target > 0),
  progress integer not null default 0 check (progress >= 0),
  reward integer not null check (reward between 0 and 100),
  completed_at timestamptz,
  claimed_at timestamptz,
  primary key (user_id, mission_date, mission_id),
  check (claimed_at is null or completed_at is not null)
);

create table public.user_achievements (
  user_id uuid not null references auth.users(id) on delete cascade,
  achievement_id text not null references public.achievement_catalog(id),
  progress integer not null default 0 check (progress >= 0),
  unlocked_at timestamptz,
  claimed_at timestamptz,
  primary key (user_id, achievement_id),
  check (claimed_at is null or unlocked_at is not null)
);

create table public.player_streaks (
  user_id uuid primary key references auth.users(id) on delete cascade,
  current_streak integer not null default 0 check (current_streak >= 0),
  best_streak integer not null default 0 check (best_streak >= 0),
  last_qualifying_date date,
  updated_at timestamptz not null default now()
);

create index daily_challenge_rank_idx on public.daily_challenge_results
  (challenge_date, score desc, height desc, played_at, id);
create index daily_challenge_user_idx on public.daily_challenge_results
  (user_id, challenge_date desc, attempt_number);
create index run_progression_recorded_idx on public.run_progression
  (user_id, recorded_at desc);

alter table public.achievement_catalog enable row level security;
alter table public.run_progression enable row level security;
alter table public.daily_challenge_results enable row level security;
alter table public.daily_missions enable row level security;
alter table public.user_achievements enable row level security;
alter table public.player_streaks enable row level security;

revoke all on public.achievement_catalog, public.run_progression,
  public.daily_challenge_results, public.daily_missions,
  public.user_achievements, public.player_streaks from public, anon, authenticated;
revoke all on sequence public.daily_challenge_results_id_seq
  from public, anon, authenticated;
grant select on public.achievement_catalog to authenticated;
grant select on public.run_progression, public.daily_challenge_results,
  public.daily_missions, public.user_achievements, public.player_streaks
  to authenticated;

create policy achievement_catalog_read_active on public.achievement_catalog
  for select to authenticated using (is_active);
create policy run_progression_select_own on public.run_progression
  for select to authenticated using ((select auth.uid()) = user_id);
create policy daily_results_select_own on public.daily_challenge_results
  for select to authenticated using ((select auth.uid()) = user_id);
create policy daily_missions_select_own on public.daily_missions
  for select to authenticated using ((select auth.uid()) = user_id);
create policy user_achievements_select_own on public.user_achievements
  for select to authenticated using ((select auth.uid()) = user_id);
create policy player_streaks_select_own on public.player_streaks
  for select to authenticated using ((select auth.uid()) = user_id);

create function sky_hopper_private.daily_seed(p_date date)
returns integer language sql immutable set search_path = ''
as $$
  select mod(
    ((extract(year from p_date)::bigint * 10000
      + extract(month from p_date)::bigint * 100
      + extract(day from p_date)::bigint) * 1103515245 + 12345),
    2147483647
  )::integer;
$$;

create function sky_hopper_private.ensure_progression(
  p_user uuid,
  p_date date
)
returns void language plpgsql security definer set search_path = ''
as $$
declare
  v_day bigint := p_date - date '1970-01-01';
  v_coin_target integer := 15 + mod(v_day, 3)::integer * 5;
  v_score_target integer := 600 + mod(v_day, 3)::integer * 200;
  v_style integer := mod(v_day, 5)::integer;
begin
  insert into public.daily_missions
    (user_id, mission_date, mission_id, title, description, metric, target, reward)
  values
    (p_user, p_date, 'collect_coins', 'POCKET CHANGE',
      'Collect ' || v_coin_target || ' coins', 'coins', v_coin_target, 5),
    (p_user, p_date, 'reach_score', 'CLIMB HIGH',
      'Reach score ' || v_score_target, 'score', v_score_target, 10)
  on conflict (user_id, mission_date, mission_id) do nothing;

  insert into public.daily_missions
    (user_id, mission_date, mission_id, title, description, metric, target, reward)
  values (
    p_user, p_date,
    case v_style when 0 then 'perfect_landings' when 1 then 'perfect_streak'
      when 2 then 'near_misses' when 3 then 'moving_landings' else 'reach_storm' end,
    case v_style when 0 then 'CENTER STAGE' when 1 then 'TRIPLE PERFECT'
      when 2 then 'CLOSE CALLS' when 3 then 'MOVING TARGET' else 'WEATHER THE STORM' end,
    case v_style when 0 then 'Make 3 perfect landings'
      when 1 then 'Reach a perfect streak of 3'
      when 2 then 'Record 2 near misses'
      when 3 then 'Land on 3 moving platforms'
      else 'Reach the Storm biome' end,
    case v_style when 0 then 'perfect_landings' when 1 then 'perfect_streak'
      when 2 then 'near_misses' when 3 then 'moving_landings' else 'reach_storm' end,
    case when v_style in (2) then 2 else 3 end,
    10
  ) on conflict (user_id, mission_date, mission_id) do nothing;

  -- Storm is boolean progress, not three visits.
  if v_style = 4 then
    update public.daily_missions set target = 1
      where user_id = p_user and mission_date = p_date and mission_id = 'reach_storm';
  end if;

  insert into public.user_achievements(user_id, achievement_id)
    select p_user, a.id from public.achievement_catalog a where a.is_active
  on conflict (user_id, achievement_id) do nothing;
  insert into public.player_streaks(user_id) values (p_user)
  on conflict (user_id) do nothing;
end;
$$;

create function sky_hopper_private.apply_run_progression(
  p_user uuid,
  p_run_id uuid,
  p_score integer,
  p_coins integer,
  p_perfect_landings integer,
  p_best_perfect_streak integer,
  p_near_misses integer,
  p_moving_landings integer,
  p_highest_biome integer,
  p_is_daily boolean
)
returns void language plpgsql security definer set search_path = ''
as $$
declare
  v_today date := (statement_timestamp() at time zone 'utc')::date;
  v_inserted integer;
  v_gameplay_coins integer;
  v_daily_days integer;
begin
  insert into public.run_progression
    (user_id, run_id, perfect_landings, best_perfect_streak, near_misses,
      moving_landings, highest_biome, is_daily)
  values (p_user, p_run_id, p_perfect_landings, p_best_perfect_streak,
    p_near_misses, p_moving_landings, p_highest_biome, p_is_daily)
  on conflict (user_id, run_id) do nothing;
  get diagnostics v_inserted = row_count;
  if v_inserted = 0 then return; end if;

  perform sky_hopper_private.ensure_progression(p_user, v_today);

  update public.daily_missions m set
    progress = least(m.target, case m.metric
      when 'coins' then m.progress + p_coins
      when 'score' then greatest(m.progress, p_score)
      when 'perfect_landings' then m.progress + p_perfect_landings
      when 'perfect_streak' then greatest(m.progress, p_best_perfect_streak)
      when 'near_misses' then m.progress + p_near_misses
      when 'moving_landings' then m.progress + p_moving_landings
      when 'reach_storm' then greatest(m.progress, case when p_highest_biome >= 2 then 1 else 0 end)
      else m.progress end),
    completed_at = case
      when completed_at is null and case m.metric
        when 'coins' then m.progress + p_coins
        when 'score' then greatest(m.progress, p_score)
        when 'perfect_landings' then m.progress + p_perfect_landings
        when 'perfect_streak' then greatest(m.progress, p_best_perfect_streak)
        when 'near_misses' then m.progress + p_near_misses
        when 'moving_landings' then m.progress + p_moving_landings
        when 'reach_storm' then greatest(m.progress, case when p_highest_biome >= 2 then 1 else 0 end)
        else m.progress end >= m.target then now() else completed_at end
  where m.user_id = p_user and m.mission_date = v_today;

  select coalesce(sum(s.coins_collected), 0)::integer into v_gameplay_coins
    from public.game_scores s where s.user_id = p_user;
  select count(distinct r.challenge_date)::integer into v_daily_days
    from public.daily_challenge_results r where r.user_id = p_user;

  update public.user_achievements u set progress = greatest(u.progress,
    case u.achievement_id
      when 'first_flight' then 1
      when 'cloud_climber' then p_score
      when 'storm_chaser' then case when p_highest_biome >= 2 then 1 else 0 end
      when 'night_rider' then case when p_highest_biome >= 3 then 1 else 0 end
      when 'to_the_stars' then case when p_highest_biome >= 4 then 1 else 0 end
      when 'perfectionist' then p_best_perfect_streak
      when 'daredevil' then u.progress + p_near_misses
      when 'coin_collector' then v_gameplay_coins
      when 'high_flyer' then p_score
      when 'daily_player' then case when p_is_daily then 1 else 0 end
      when 'consistent' then v_daily_days
      else u.progress end)
  where u.user_id = p_user;

  update public.user_achievements u set unlocked_at = now()
    from public.achievement_catalog a
    where u.user_id = p_user and a.id = u.achievement_id
      and u.unlocked_at is null and u.progress >= a.target;

  -- Achievement cosmetics are granted automatically and never charge coins.
  insert into public.user_skins(user_id, skin_id)
    select p_user, 'stormbound' where exists (
      select 1 from public.user_achievements
      where user_id = p_user and achievement_id = 'storm_chaser' and unlocked_at is not null)
  on conflict (user_id, skin_id) do nothing;
  insert into public.user_skins(user_id, skin_id)
    select p_user, 'starlight' where exists (
      select 1 from public.user_achievements
      where user_id = p_user and achievement_id = 'to_the_stars' and unlocked_at is not null)
  on conflict (user_id, skin_id) do nothing;

  insert into public.player_streaks
    (user_id, current_streak, best_streak, last_qualifying_date, updated_at)
  values (p_user, 1, 1, v_today, now())
  on conflict (user_id) do update set
    current_streak = case
      when public.player_streaks.last_qualifying_date = v_today
        then public.player_streaks.current_streak
      when public.player_streaks.last_qualifying_date = v_today - 1
        then public.player_streaks.current_streak + 1
      else 1 end,
    best_streak = greatest(public.player_streaks.best_streak, case
      when public.player_streaks.last_qualifying_date = v_today
        then public.player_streaks.current_streak
      when public.player_streaks.last_qualifying_date = v_today - 1
        then public.player_streaks.current_streak + 1
      else 1 end),
    last_qualifying_date = v_today,
    updated_at = now();
end;
$$;

create function public.submit_progression_result(
  p_run_id uuid, p_score integer, p_height integer, p_coins_collected integer,
  p_perfect_landings integer, p_best_perfect_streak integer,
  p_near_misses integer, p_moving_landings integer, p_highest_biome integer
)
returns jsonb language plpgsql security definer set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_profile public.profiles%rowtype;
  v_score public.game_scores%rowtype;
begin
  if v_user is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  if p_run_id is null or p_score is null or p_height is null
    or p_coins_collected is null or p_perfect_landings is null
    or p_best_perfect_streak is null or p_near_misses is null
    or p_moving_landings is null or p_highest_biome is null
    or p_score < 0 or p_height < 0 or p_coins_collected < 0
    or p_perfect_landings not between 0 and 10000
    or p_best_perfect_streak not between 0 and 10
    or p_near_misses not between 0 and 10000
    or p_moving_landings not between 0 and 10000
    or p_highest_biome not between 0 and 4 then
    raise exception 'Invalid game result' using errcode = '22023';
  end if;
  select * into v_profile from public.profiles where id = v_user for update;
  if not found then raise exception 'Profile unavailable' using errcode = 'P0002'; end if;
  select * into v_score from public.game_scores where user_id = v_user and run_id = p_run_id;
  if found then
    if v_score.score <> p_score or v_score.height <> p_height
      or v_score.coins_collected <> p_coins_collected then
      raise exception 'Run ID already used for another result' using errcode = '22023';
    end if;
  else
    if v_profile.total_coins::bigint + p_coins_collected::bigint > 2147483647 then
      raise exception 'Coin balance limit reached' using errcode = '22003';
    end if;
    insert into public.game_scores(user_id, run_id, score, height, coins_collected)
      values (v_user, p_run_id, p_score, p_height, p_coins_collected)
      returning * into v_score;
    update public.profiles set total_coins = total_coins + p_coins_collected
      where id = v_user returning * into v_profile;
  end if;
  perform sky_hopper_private.apply_run_progression(v_user, p_run_id, p_score,
    p_coins_collected, p_perfect_landings, p_best_perfect_streak,
    p_near_misses, p_moving_landings, p_highest_biome, false);
  return jsonb_build_object('run_id', v_score.run_id, 'game_score_id', v_score.id,
    'saved_score', v_score.score, 'saved_height', v_score.height,
    'coins_collected', v_score.coins_collected,
    'new_total_coins', v_profile.total_coins,
    'profile_updated_at', v_profile.updated_at, 'played_at', v_score.played_at);
end;
$$;

create function public.submit_daily_challenge_result(
  p_challenge_date date, p_run_id uuid, p_score integer, p_height integer,
  p_coins_collected integer, p_perfect_landings integer,
  p_best_perfect_streak integer, p_near_misses integer,
  p_moving_landings integer, p_highest_biome integer
)
returns jsonb language plpgsql security definer set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_today date := (statement_timestamp() at time zone 'utc')::date;
  v_profile public.profiles%rowtype;
  v_score public.game_scores%rowtype;
  v_daily public.daily_challenge_results%rowtype;
  v_attempt integer;
begin
  if v_user is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  if p_challenge_date is distinct from v_today then
    raise exception 'Daily challenge has changed' using errcode = 'SH003';
  end if;
  if p_run_id is null or p_score is null or p_height is null
    or p_coins_collected is null or p_perfect_landings is null
    or p_best_perfect_streak is null or p_near_misses is null
    or p_moving_landings is null or p_highest_biome is null
    or p_score < 0 or p_height < 0 or p_coins_collected < 0
    or p_perfect_landings not between 0 and 10000
    or p_best_perfect_streak not between 0 and 10
    or p_near_misses not between 0 and 10000
    or p_moving_landings not between 0 and 10000
    or p_highest_biome not between 0 and 4 then
    raise exception 'Invalid game result' using errcode = '22023';
  end if;
  select * into v_profile from public.profiles where id = v_user for update;
  if not found then raise exception 'Profile unavailable' using errcode = 'P0002'; end if;
  select * into v_daily from public.daily_challenge_results
    where user_id = v_user and run_id = p_run_id;
  if found then
    select * into v_score from public.game_scores where id = v_daily.game_score_id;
    if v_daily.challenge_date <> p_challenge_date or v_score.score <> p_score
      or v_score.height <> p_height or v_score.coins_collected <> p_coins_collected then
      raise exception 'Run ID already used for another result' using errcode = '22023';
    end if;
  else
    select count(*) + 1 into v_attempt from public.daily_challenge_results
      where user_id = v_user and challenge_date = v_today;
    if v_attempt > 3 then raise exception 'Daily attempts exhausted' using errcode = 'SH003'; end if;
    if exists (select 1 from public.game_scores where user_id = v_user and run_id = p_run_id) then
      raise exception 'Run ID already used for another result' using errcode = '22023';
    end if;
    if v_profile.total_coins::bigint + p_coins_collected::bigint > 2147483647 then
      raise exception 'Coin balance limit reached' using errcode = '22003';
    end if;
    insert into public.game_scores(user_id, run_id, score, height, coins_collected)
      values (v_user, p_run_id, p_score, p_height, p_coins_collected)
      returning * into v_score;
    insert into public.daily_challenge_results
      (user_id, challenge_date, run_id, game_score_id, attempt_number, score, height)
      values (v_user, v_today, p_run_id, v_score.id, v_attempt, p_score, p_height)
      returning * into v_daily;
    update public.profiles set total_coins = total_coins + p_coins_collected
      where id = v_user returning * into v_profile;
  end if;
  perform sky_hopper_private.apply_run_progression(v_user, p_run_id, p_score,
    p_coins_collected, p_perfect_landings, p_best_perfect_streak,
    p_near_misses, p_moving_landings, p_highest_biome, true);
  return jsonb_build_object('run_id', v_score.run_id, 'game_score_id', v_score.id,
    'saved_score', v_score.score, 'saved_height', v_score.height,
    'coins_collected', v_score.coins_collected,
    'new_total_coins', v_profile.total_coins,
    'profile_updated_at', v_profile.updated_at, 'played_at', v_score.played_at,
    'challenge_date', v_daily.challenge_date, 'attempt_number', v_daily.attempt_number);
end;
$$;

create function public.claim_progression_reward(p_reward_type text, p_reward_id text)
returns jsonb language plpgsql security definer set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_today date := (statement_timestamp() at time zone 'utc')::date;
  v_profile public.profiles%rowtype;
  v_reward integer;
  v_claimed timestamptz;
  v_already boolean;
begin
  if v_user is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  if p_reward_type not in ('mission', 'achievement')
    or p_reward_id !~ '^[a-z][a-z0-9_]{0,39}$' then
    raise exception 'Invalid reward' using errcode = '22023';
  end if;
  select * into v_profile from public.profiles where id = v_user for update;
  if not found then raise exception 'Profile unavailable' using errcode = 'P0002'; end if;
  perform sky_hopper_private.ensure_progression(v_user, v_today);
  if p_reward_type = 'mission' then
    select reward, claimed_at into v_reward, v_claimed from public.daily_missions
      where user_id = v_user and mission_date = v_today and mission_id = p_reward_id
        and completed_at is not null for update;
    if not found then raise exception 'Reward unavailable' using errcode = 'SH004'; end if;
    v_already := v_claimed is not null;
    if not v_already then update public.daily_missions set claimed_at = now()
      where user_id = v_user and mission_date = v_today and mission_id = p_reward_id; end if;
  else
    select a.reward, u.claimed_at into v_reward, v_claimed
      from public.user_achievements u join public.achievement_catalog a
        on a.id = u.achievement_id
      where u.user_id = v_user and u.achievement_id = p_reward_id
        and u.unlocked_at is not null for update of u;
    if not found then raise exception 'Reward unavailable' using errcode = 'SH004'; end if;
    v_already := v_claimed is not null;
    if not v_already then update public.user_achievements set claimed_at = now()
      where user_id = v_user and achievement_id = p_reward_id; end if;
  end if;
  if not v_already then
    if v_profile.total_coins::bigint + v_reward::bigint > 2147483647 then
      raise exception 'Coin balance limit reached' using errcode = '22003';
    end if;
    update public.profiles set total_coins = total_coins + v_reward
      where id = v_user returning * into v_profile;
  end if;
  return jsonb_build_object('reward_type', p_reward_type, 'reward_id', p_reward_id,
    'reward_granted', case when v_already then 0 else v_reward end,
    'new_total_coins', v_profile.total_coins, 'already_claimed', v_already);
end;
$$;

create function public.get_progression_snapshot()
returns jsonb language plpgsql security definer set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_today date := (statement_timestamp() at time zone 'utc')::date;
  v_week_start date := date_trunc('week', statement_timestamp() at time zone 'utc')::date;
  v_result jsonb;
begin
  if v_user is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  perform sky_hopper_private.ensure_progression(v_user, v_today);
  select jsonb_build_object(
    'challenge_date', v_today,
    'challenge_seed', sky_hopper_private.daily_seed(v_today),
    'attempts_used', (select count(*) from public.daily_challenge_results
      where user_id = v_user and challenge_date = v_today),
    'attempt_limit', 3,
    'daily_best', coalesce((select max(score) from public.daily_challenge_results
      where user_id = v_user and challenge_date = v_today), 0),
    'weekly_best', coalesce((select max(score) from public.game_scores
      where user_id = v_user and played_at >= v_week_start::timestamp at time zone 'utc'
        and played_at < (v_week_start + 7)::timestamp at time zone 'utc'), 0),
    'all_time_best', coalesce((select max(score) from public.game_scores where user_id = v_user), 0),
    'top_daily_score', coalesce((select max(score) from public.daily_challenge_results
      where challenge_date = v_today), 0),
    'current_streak', coalesce((select case
      when last_qualifying_date >= v_today - 1 then current_streak else 0 end
      from public.player_streaks where user_id = v_user), 0),
    'best_streak', coalesce((select best_streak from public.player_streaks where user_id = v_user), 0),
    'missions', coalesce((select jsonb_agg(jsonb_build_object(
      'id', mission_id, 'title', title, 'description', description,
      'progress', progress, 'target', target, 'reward', reward,
      'completed', completed_at is not null, 'claimed', claimed_at is not null)
      order by mission_id) from public.daily_missions
      where user_id = v_user and mission_date = v_today), '[]'::jsonb),
    'achievements', coalesce((select jsonb_agg(jsonb_build_object(
      'id', a.id, 'title', a.name, 'description', a.description, 'icon', a.icon,
      'progress', u.progress, 'target', a.target, 'reward', a.reward,
      'completed', u.unlocked_at is not null, 'claimed', u.claimed_at is not null)
      order by a.sort_order) from public.user_achievements u
      join public.achievement_catalog a on a.id = u.achievement_id
      where u.user_id = v_user and a.is_active), '[]'::jsonb)
  ) into v_result;
  return v_result;
end;
$$;

create function public.get_competition_leaderboard(
  p_scope text, p_limit integer default 50
)
returns table (
  rank bigint, display_name text, avatar_url text, best_score integer,
  best_height integer, played_at timestamptz, is_current_user boolean
)
language plpgsql stable security definer set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_today date := (statement_timestamp() at time zone 'utc')::date;
  v_week_start timestamptz := date_trunc('week', statement_timestamp() at time zone 'utc') at time zone 'utc';
begin
  if v_user is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  if p_scope not in ('daily', 'weekly', 'all_time') or p_limit not between 1 and 100 then
    raise exception 'Invalid leaderboard request' using errcode = '22023';
  end if;
  return query
    with candidates as (
      select s.user_id, s.score, s.height, s.played_at, s.id
      from public.game_scores s
      where (p_scope = 'all_time')
        or (p_scope = 'weekly' and s.played_at >= v_week_start and s.played_at < v_week_start + interval '7 days')
      union all
      select d.user_id, d.score, d.height, d.played_at, d.id
      from public.daily_challenge_results d where p_scope = 'daily' and d.challenge_date = v_today
    ), personal_best as (
      select c.*, row_number() over (
        partition by c.user_id order by c.score desc, c.height desc, c.played_at, c.id) as personal_rank
      from candidates c
    ), ranked as (
      select b.*, row_number() over (
        order by b.score desc, b.height desc, b.played_at, b.id) as global_rank
      from personal_best b where b.personal_rank = 1
    )
    select r.global_rank,
      coalesce(nullif(btrim(p.display_name), ''), 'Player'),
      case when p.avatar_url ~ '^https://' then p.avatar_url else null end,
      r.score, r.height, r.played_at, r.user_id = v_user
    from ranked r join public.profiles p on p.id = r.user_id
    order by r.global_rank limit p_limit;
end;
$$;

-- Two achievement-only cosmetics. They are auto-granted by progression.
alter table public.skin_catalog add column unlock_achievement_id text
  references public.achievement_catalog(id);
insert into public.skin_catalog
  (id, name, description, cost, primary_color, secondary_color, accent_color,
   sort_order, unlock_achievement_id)
values
  ('stormbound', 'Stormbound', 'Earned by Storm Chasers.', 0, '#6F86A8', '#33465F', '#D7ECFF', 5, 'storm_chaser'),
  ('starlight', 'Starlight', 'Earned by reaching Space.', 0, '#D8D2FF', '#6655A8', '#9CF4FF', 6, 'to_the_stars');

create or replace function public.unlock_skin(p_skin_id text)
returns jsonb language plpgsql security definer set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_skin public.skin_catalog%rowtype;
  v_profile public.profiles%rowtype;
  v_unlocked timestamptz;
  v_owned boolean;
begin
  if v_user is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  select * into v_skin from public.skin_catalog where id = p_skin_id and is_active;
  if not found then raise exception 'Skin unavailable' using errcode = '22023'; end if;
  if v_skin.unlock_achievement_id is not null and not exists (
    select 1 from public.user_achievements where user_id = v_user
      and achievement_id = v_skin.unlock_achievement_id and unlocked_at is not null) then
    raise exception 'Achievement required' using errcode = 'SH004';
  end if;
  select * into v_profile from public.profiles where id = v_user for update;
  if not found then raise exception 'Profile unavailable' using errcode = 'P0002'; end if;
  select unlocked_at into v_unlocked from public.user_skins
    where user_id = v_user and skin_id = p_skin_id;
  v_owned := found;
  if not v_owned then
    if v_profile.total_coins < v_skin.cost then raise exception 'Not enough coins' using errcode = 'SH001'; end if;
    update public.profiles set total_coins = total_coins - v_skin.cost
      where id = v_user returning * into v_profile;
    insert into public.user_skins(user_id, skin_id) values (v_user, p_skin_id)
      returning unlocked_at into v_unlocked;
  end if;
  return jsonb_build_object('skin_id', p_skin_id, 'already_owned', v_owned,
    'cost_charged', case when v_owned then 0 else v_skin.cost end,
    'new_total_coins', v_profile.total_coins, 'unlocked_at', v_unlocked,
    'profile_updated_at', v_profile.updated_at);
end;
$$;

revoke all on function sky_hopper_private.daily_seed(date),
  sky_hopper_private.ensure_progression(uuid, date),
  sky_hopper_private.apply_run_progression(uuid, uuid, integer, integer,
    integer, integer, integer, integer, integer, boolean)
  from public, anon, authenticated;
revoke all on function public.submit_progression_result(uuid, integer, integer,
  integer, integer, integer, integer, integer, integer),
  public.submit_daily_challenge_result(date, uuid, integer, integer, integer,
    integer, integer, integer, integer, integer),
  public.claim_progression_reward(text, text),
  public.get_progression_snapshot(),
  public.get_competition_leaderboard(text, integer)
  from public, anon, authenticated, service_role;
grant execute on function public.submit_progression_result(uuid, integer, integer,
  integer, integer, integer, integer, integer, integer),
  public.submit_daily_challenge_result(date, uuid, integer, integer, integer,
    integer, integer, integer, integer, integer),
  public.claim_progression_reward(text, text),
  public.get_progression_snapshot(),
  public.get_competition_leaderboard(text, integer)
  to authenticated;
